version: '3.8'

services:
  python-neuron:
    build: .
    container_name: findawise-python-neuron
    restart: unless-stopped
    environment:
      - FEDERATION_URL=http://host.docker.internal:5000
      - NEURON_ID=python-neuron-docker-001
      - NEURON_NAME=Python Docker Neuron
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - HEARTBEAT_INTERVAL=60
      - COMMAND_CHECK_INTERVAL=30
      - ANALYTICS_INTERVAL=300
      - METRICS_ENABLED=true
      - METRICS_PORT=8080
    ports:
      - "8080:8080"  # Metrics endpoint
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - neuron-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  neuron-network:
    driver: bridge